### ISSUE TITLE
Issue with URL passed from simplified webpage

### ISSUE THREAD

**Issue by EDIflyer** [nayfield/GrazeTen#14]
I've noticed that the URL passed from simplified webpages (example below) doesn't load properly, it just shows the Google home page. Links opened from straight A+I pages seem to be only the URL themselves and work fine.

V3.1.3

https://www.google.com/?lite_url=https://electrek.co/2019/11/27/tesla-cybertruck-is-disrupting-the-holiday-season-see-ugly-xmas-sweaters/&s=1&f=1&ts=1579993923&sig=ACgcqhpSAC4lBQ5pgFHvqQP21I9byaLLnw

**Comment by nayfield** [comment]
(note - i  have not used the mobilizers)

This is using the GWT mobilizer?

can you post steps to reproduce (including any setup change you make)?  (and verify that the same item is OK with GrazeRSS?)


I did this and it seemed fine:

1. change settings to sync "articles+images+simplified web" (from default A+I)
2. open item (noted it was simplified web view now)
3. long press on link and open in browser
4. press on link to go to it inside graze

both 3 and 4 worked for me.

**Comment by EDIflyer** [comment]
Yes, GWT
Settings as per other bug
With regards 1-4 it only works fine if it hasn't synced the simplified webview. If you just change setting without syncing it seems to load it there and then in webview and the links work. However if it has already been synced then clicking on a link just shows grey Google homepage... 
![Screenshot_20200126-101831](https://user-images.githubusercontent.com/13610277/73133792-90786b80-4025-11ea-8587-ea5b7eb7dd77.jpg)

My suspicion is when the page is retrieved from GWT it is doing something to the links (adding that bit at the start) that is then causing the problem. This probably needs stripped from the URLs. If viewed 'live' rather than synced it doesn't do this.

I tried in GrazeRSS and the behaviour is the same when single tapping links (getting grey Google page) however pressing long press to open a link in the webbrowser never worked (just caused a crash) therefore I could never use the functionality and if I wanted to view a link I just had to open the original article in webbrowser then click the link there.

**Comment by EDIflyer** [comment]
FYI was the error dump in GrazeRSS when trying to long click a url and open in browser. Not sure how relevant it is now it doesn't crash in GrazeTEN.

Sorry!

GrazeRSS hit a wall. Please send this mail, so that the developer can analyze/fix the issue.
If it is not too much to ask, please add to this mail what you just did between the following lines:

-------


-------
-- Time: Sun Jan 26 10:17:05 GMT 2020
-- Android Version: sdk=28, release=9, inc=1909112330
-- Memory free: 7.11MB total: 14.06MB max: 256.00MB
-- BuildD: ONEPLUS A6003_22_190911 
-- Manufacturer: OnePlus 
-- Device: OnePlus6
-- Model: ONEPLUS A6003
-- NewsRob Version: 2.0.10/210
-- Configured Capacity: 500
--        Keep Starred: 100
--        Keep Shared: 20
--        Keep Notes: 5
-- Current Article Count: 273
-- Action Bar Location: top
-- Days installed: 611
-- Orientation: 0
-- StorageAdapter: SdCardStorageAdapter
--   MB available: 4033
-- Phone Memory MB available: 4033.0
-- Sync Auto enabled: false
--      Unread Only: true
--      Delete Read: true
--      NewsRob only: false
--      Offline use: yes
--      Offline Def: 2
-- FireModelUpdate in progress: false
-- LastActivity: ShowArticleActivity.
-- Stacktrace:(1516)
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:915)
at android.app.ContextImpl.startActivity(ContextImpl.java:891)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:166)
at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1169)
at android.widget.AdapterView.performItemClick(AdapterView.java:318)
at android.widget.AbsListView.performItemClick(AbsListView.java:1201)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3178)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by nayfield** [comment]
Yes that crash is #8 which should be fixed throughout grazeten.  

Sounds like the cached simplified link issue was in grazerss too ... But I will leave this open in case somebody can fix it

**Comment by nayfield** [comment]
Note to anybody who wants to fix this issue ... Maybe there's some hard coding translation of cached links ?  Likely Google changed the URL for mobilizer in the last decade

**Comment by EDIflyer** [comment]
Not sure how easy to fix but found that it should be googleweblight.com rather than google.com.

I changed it in my original URL above and it worked fine
https://googleweblight.com/?lite_url=https://electrek.co/2019/11/27/tesla-cybertruck-is-disrupting-the-holiday-season-see-ugly-xmas-sweaters/&s=1&f=1&ts=1580053815&re=1&sig=ACgcqhqUXAiKWMOm792x_N4uJpENdTYF4A

Found the info here: https://rehmann.co/blog/how-does-googleweblight-work/

**Comment by nayfield** [comment]
app/src/main/java/com/grazeten/Entry.java:    mobilizersMap.put("gwt", "http://www.google.com/gwt/n?u=");

I think changing that string would do it.

**Comment by nayfield** [comment]
yes pretty sure because there is code that reconstructs urls using that base

give me 5 min

**Comment by nayfield** [comment]
test with 3.1.4 and let me know.

**Comment by EDIflyer** [comment]
Looks to be working perfectly!
As an option you could offer a config in settings to let user pick between Google Weblight and directly just opening the URL but probably best to leave it all as weblight for simplicity.
Great work :)
