### ISSUE TITLE
Has anything changed re GWT 

### ISSUE THREAD

**Issue by EDIflyer** [nayfield/GrazeTen#18]
Appreciate GWT not fully supported but noted recently that when I go to synced articles that have been set to SWP that I'm able to read it but as I scroll down I get a blue spinner appearing? See screenshot...

![Screenshot_20200129-183414](https://user-images.githubusercontent.com/13610277/73386134-41049a80-42c6-11ea-9c8c-e9a0823d58f9.jpg)

NB the sync completed fine and this has happened for a couple of days now.

**Comment by nayfield** [comment]
Is this still an issue?  Or duplicate of #14  ?

**Comment by EDIflyer** [comment]
No it was a different issue to #14 as it was at least showing content, it just had a constant spinner. Not seen it in months though so suspect it was a GWT issue that's now been sorted 👍
